steps:
- name: 'ubuntu'
  args: ['ls', '-la']
- name: 'gcr.io/${PROJECT_ID}/hugo'
- name: 'ubuntu'
  args: ['ls', '-la public']
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'public/'
    - 'gs://${_BUCKET_NAME}'
