steps:
- name: 'gcr.io/${PROJECT_ID}/hugo'
  volumes:
    - name: 'public'
      path: public
- name: 'gcr.io/cloud-builders/gsutil'
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'public/'
    - 'gs://${_BUCKET_NAME}'
  volumes:
    - name: 'public'
      path: public
