steps:
- id: 'submodules'
  name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git submodule init
    git submodule update
- id: 'hugo'
  name: 'gcr.io/${PROJECT_ID}/hugo'
  args: ["--theme=hugo-swift-theme"]
  waitFor: ['submodules']
- id: 'publish'
  name: 'gcr.io/cloud-builders/gsutil'
  args: 
  - '-m'
  - 'rsync'
  - '-r'
  - '-c'
  - '-d'
  - './public/.'
  - 'gs://${_BUCKET_NAME}'
  waitFor: ['hugo']
