steps:
- name: 'gcr.io/${PROJECT_ID}/hugo'
  args: ["--theme=hugo-swift-theme", "--destination=/website"]
  volumes:
  - name: 'persistent'
    path: '/website'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ["-m", "rsync", "-r", "-c", "-d", "/website/.", "gs://${_BUCKET_NAME}"]
  volumes:
  - name: 'persistent'
    path: '/website'
